name: "Notion to GitHub Comments"
description: "Extracts Notion page/database info from GitHub PR/Issue descriptions and posts formatted Markdown content as GitHub comments"
author: "wasabeef"
inputs:
  notion-token:
    description: "Notion API Integration Token"
    required: true
  github-token:
    description: "GitHub Token"
    required: true
    default: "${{ github.token }}"
outputs:
  comment-url:
    description: "The URL of the created or updated comment."
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "book"
  color: "blue"
