name: Notion PR AI Context
on:
  pull_request:
    types: [opened, edited]
jobs:
  add-notion-context:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Add Notion Context
        uses: ./
        with:
          notion-token: ${{ secrets.NOTION_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
