name: Test Notion to PR Comments Action

on:
  workflow_dispatch: # Manual testing only
    inputs:
      pr_number:
        description: "PR number to test (optional)"
        required: false
        type: string
      test_url:
        description: "Notion URL to test (optional)"
        required: false
        type: string

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Test Notion to PR Comments
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Import .tool-versions
        uses: wasabeef/import-asdf-tool-versions-action@v1.1.0
        id: asdf # ID to reference outputs

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ steps.asdf.outputs.bun }} # Use Bun version from .tool-versions

      - name: Install dependencies
        run: bun install

      - name: Build action
        run: bun run build # Compile TypeScript

      - name: Run Notion to PR Comments Action
        id: notion-to-github-comments
        uses: ./
        with:
          notion-token: ${{ secrets.NOTION_TOKEN }} # Secret that needs to be manually configured
          github-token: ${{ secrets.GITHUB_TOKEN }} # GitHub's automatic token

      - name: Verify action completion
        run: |
          echo "🧪 Manual test completed"
          echo "✅ Action outcome: ${{ steps.notion-to-github-comments.outcome }}"
          if [ "${{ steps.notion-to-github-comments.outcome }}" = "success" ]; then
            echo "📝 Comment URL: ${{ steps.notion-to-github-comments.outputs.comment-url }}"
          fi
