name: Test Notion to PR Comments Action

on:
  workflow_dispatch:  # Allow manual dispatch
  pull_request:
    types: [opened, edited, reopened]  # Trigger on PR creation/edit/reopen

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Test Notion to PR Comments
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Import .tool-versions
        uses: wasabeef/import-asdf-tool-versions-action@v1.0.3
        id: asdf # ID to reference outputs

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ steps.asdf.outputs.bun }} # Use Bun version from .tool-versions

      - name: Install dependencies
        run: bun install

      - name: Build action
        run: bun run build  # Compile TypeScript

      - name: Run Notion to PR Comments Action
        id: notion-to-pr-comments
        uses: ./
        with:
          notion-token: ${{ secrets.NOTION_TOKEN }}  # Secret that needs to be manually configured
          github-token: ${{ secrets.GITHUB_TOKEN }}  # GitHub's automatic token

      - name: Verify comment creation
        if: steps.notion-to-pr-comments.outcome == 'success'
        run: |
          echo "Action completed successfully"
          echo "Comment URL: ${{ steps.notion-to-pr-comments.outputs.comment-url }}"
